# Analyse des données foncières à Paris entre 2020 et 2025

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

df = pd.read_csv("data/silver/dvf_75_nettoye.csv", low_memory=False)

print(f"Données chargées : {df.shape[0]:,} lignes et {df.shape[1]} colonnes")
df.head()

Données chargées : 204,125 lignes et 41 colonnes

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,prix_m2
0,2020-814508,2020-07-01,1,Vente,148000.0,105.0,NaN,RUE VIEILLE DU TEMPLE,9783,75003.0,...,12.0,1.0,NaN,NaN,NaN,NaN,NaN,2.361559,48.860524,12333.333333
1,2020-814510,2020-07-01,1,Vente,270000.0,9.0,NaN,RUE HEROLD,4619,75001.0,...,27.0,2.0,NaN,NaN,NaN,NaN,NaN,2.341301,48.864895,10000.000000
2,2020-814514,2020-07-06,1,Vente,2603550.0,3.0,NaN,RUE DE L ECHELLE,3082,75001.0,...,137.0,6.0,NaN,NaN,NaN,NaN,NaN,2.333735,48.863683,19004.014599
3,2020-814515,2020-07-02,1,Vente,1112000.0,98.0,NaN,RUE SAINT DENIS,8525,75001.0,...,84.0,4.0,NaN,NaN,NaN,NaN,NaN,2.350170,48.863265,13238.095238
4,2020-814517,2020-07-02,1,Vente,1670000.0,20.0,NaN,RUE DES BONS ENFANTS,1105,75001.0,...,120.0,5.0,NaN,NaN,NaN,NaN,NaN,2.338875,48.863430,13916.666667

## Aperçu général des données

In [15]:
print("Colonnes disponibles :")
print(df.columns.tolist())

print("\nTypes des colonnes :")
print(df.dtypes)

print("\nStatistiques descriptives de base :")
df[['valeur_fonciere', 'surface_reelle_bati', 'prix_m2']].describe().round(2)

Colonnes disponibles :
['id_mutation', 'date_mutation', 'numero_disposition', 'nature_mutation', 'valeur_fonciere', 'adresse_numero', 'adresse_suffixe', 'adresse_nom_voie', 'adresse_code_voie', 'code_postal', 'code_commune', 'nom_commune', 'code_departement', 'ancien_code_commune', 'ancien_nom_commune', 'id_parcelle', 'ancien_id_parcelle', 'numero_volume', 'lot1_numero', 'lot1_surface_carrez', 'lot2_numero', 'lot2_surface_carrez', 'lot3_numero', 'lot3_surface_carrez', 'lot4_numero', 'lot4_surface_carrez', 'lot5_numero', 'lot5_surface_carrez', 'nombre_lots', 'code_type_local', 'type_local', 'surface_reelle_bati', 'nombre_pieces_principales', 'code_nature_culture', 'nature_culture', 'code_nature_culture_speciale', 'nature_culture_speciale', 'surface_terrain', 'longitude', 'latitude', 'prix_m2']

Types des colonnes :
id_mutation                         str
date_mutation                       str
numero_disposition                int64
nature_mutation                     str
valeur_fonciere                 float64
adresse_numero                  float64
adresse_suffixe                     str
adresse_nom_voie                    str
adresse_code_voie                   str
code_postal                     float64
code_commune                      int64
nom_commune                         str
code_departement                  int64
ancien_code_commune             float64
ancien_nom_commune              float64
id_parcelle                         str
ancien_id_parcelle              float64
numero_volume                   float64
lot1_numero                         str
lot1_surface_carrez             float64
lot2_numero                         str
lot2_surface_carrez             float64
lot3_numero                         str
lot3_surface_carrez             float64
lot4_numero                     float64
lot4_surface_carrez             float64
lot5_numero                     float64
lot5_surface_carrez             float64
nombre_lots                       int64
code_type_local                 float64
type_local                          str
surface_reelle_bati             float64
nombre_pieces_principales       float64
code_nature_culture                 str
nature_culture                      str
code_nature_culture_speciale        str
nature_culture_speciale             str
surface_terrain                 float64
longitude                       float64
latitude                        float64
prix_m2                         float64
dtype: object

Statistiques descriptives de base :

       valeur_fonciere  surface_reelle_bati      prix_m2
count     2.041250e+05            204125.00    204125.00
mean      3.586379e+06                68.16     76960.73
std       2.160554e+07               218.83    580307.95
min       1.500000e-01                11.00         0.00
25%       2.850000e+05                28.00      8785.71
50%       5.000000e+05                44.00     10898.67
75%       1.050000e+06                71.00     14428.57
max       7.620000e+08             28109.00  54428571.43